

#These values might be changed to constants.yml
networking:
  eaddress: 192.168.51.117
ha:
  eiface: eth0
  bindnetaddr: 192.168.51.0
  mcastaddr: 226.94.1.1
  mcastport: 5405

database:
  bufferpoolsize: 254M
kamailio:
  port: 5060
  disable_tcp: yes
  authenticate_bye: no

  multi_homed: no
  allow_peer_relay: no

  use_enum: no
  enum_suffix: e164.arpa.
  patterns:
    emergency: 112|911|999
asterisk:
  sip:
    bindport: 5070
    dtmfmode: rfc2833
  rtp:
    minport: 10000
    maxport: 20000
  voicemail:
    serveremail: voicebox@sip.sipwise.com
    maxmsg: 30
    max_msg_length: 180
    min_msg_length: 3
    maxgreet: 60
    fromstring: Voicemail server
    mailsubject: '[Voicebox] New message ${VM_MSGNUM} in voicebox ${VM_MAILBOX}'
    mailbody: 'You have received a new message from ${VM_CALLERID} in voicebox ${VM_MAILBOX} on ${VM_DATE}.'
  log:
    facility: local6
mediator:
  interval: 10
rateomat:
  splitpeakparts: 0
  loopinterval: 10
ossbss:
  htpasswd:
    - user: ngcpsoap
      pass: '{SHA}w4zj3mxbmynIQ1jsUEjSkN2z2pk='
  apache:
    port: 2443
    serveradmin: support@sipwise.com
    servername: '"myserver"'
    sslcertfile: /etc/apache2/ssl/myserver.crt
    sslcertkeyfile: /etc/apache2/ssl/myserver.pem
  provisioning:
    log_passwords: 0
    no_logline_truncate: 0
    allow_ip_as_domain: 1
    allow_numeric_usernames: 0
    tmpdir: /tmp

    faxpw_min_char: 0

    routing:
      cc_regex: '[1-9]\d{0,3}'
      ac_regex: '[1-9]\d{0,4}'
      sn_regex: '[1-9]\d+'
  logging:
    ossbss:
      facility: local0
      level: DEBUG
      identity: provisioning
    web:
      facility: local0
      level: DEBUG
    apache:
      err:
        facility: local7
        level: info
      acc:
        facility: daemon
        level: info
        identity: oss
www_admin:
  apache:
    port: 1443
    serveradmin: support@sipwise.com
    servername: '"myserver"'
    sslcertfile: /etc/apache2/ssl/myserver.crt
    sslcertkeyfile: /etc/apache2/ssl/myserver.pem
  billing_features: 1
  peering_features: 1
  voicemail_features: 1
  fax_features: 1
  conference_features: 1
  cc_dial_prefix: 00
  ac_dial_prefix: 0
  dashboard:
    enable: 1
  subscriber:
    extension_features: 0
    audiofile_features: 0
  domain:
    rewrite_features: 1
    audiofile_features: 0
    vsc_features: 0
  default_admin_settings:
    is_master: 0
    is_active: 1
    read_only: 0
    show_passwords: 1
    call_data: 0
  fees_csv:
    element_order:
      - destination
      - zone
      - zone_detail
      - onpeak_init_rate
      - onpeak_init_interval
      - onpeak_follow_rate
      - onpeak_follow_interval
      - offpeak_init_rate
      - offpeak_init_interval
      - offpeak_follow_rate
      - offpeak_follow_interval
      - use_free_time
  speed_dial_vsc_presets:
    vsc:
      - '*0'
      - '*1'
      - '*2'
      - '*3'
      - '*4'
      - '*5'
      - '*6'
      - '*7'
      - '*8'
      - '*9'
  logging:
    apache:
      err:
        facility: local7
        level: info
      acc:
        facility: daemon
        level: info
        identity: oss
www_csc:
  apache:
    port: 443
    serveradmin: support@sipwise.com
    servername: myserver
    sslcertfile: /etc/apache2/ssl/myserver.crt
    sslcertkeyfile: /etc/apache2/ssl/myserver.pem
  site_domain: sip.yourdomain.tld
  display_account_info: 0
  sip_server: sip.yourdomain.tld
  tftp_server: tftp.yourdomain.tld
  payment_features: 0
  cc_dial_prefix: 00
  ac_dial_prefix: 0
  site_config:
    title: Sipwise NGCP CSC
    default_language: en
    default_uri: '/desktop'
    languages:
      - en
      - es
    company:
      name: Your Company
      logo: 'https://some.server/path/to/logo.gif'
      hotline: ''
      city: ''
      street: ''
      phone: ''
      fax: ''
      email: ''
      webserver: ''
  main_menu:
    desktop: 1
    calllist: 1
    voicebox: 1
    addressbook: 1
    callforward: 1
    callblock: 1
    reminder: 1
    device: 0
    account: 1
  logging:
    apache:
      err:
        facility: local7
        level: info
      acc:
        facility: daemon
        level: info
        identity: csc
rtpproxy:
  minport: 30000
  maxport: 40000
sems:
  bindport: 5080
  lowport: 40001
  highport: 50000
  xmlrpcport: 8090
  vsc:
    voicemail_number: 2000
    cfu_code: 72
    cfb_code: 90
    cft_code: 92
    cfna_code: 93
    speedial_code: 50
    reminder_code: 55
rsyslog:
  external_log: 0
  external_address: 192.168.32.1
  external_proto: udp
  external_port: 514
  external_loglevel: warning
reminder:
  retries: 2
  retry_time: 60
  wait_time: 30
  sip_fromuser: reminder
  sip_fromdomain: voicebox.sipwise.local
checktools:
  sip_check_enable: 1
  mysql_check_enable: 1
  mpt_check_enable: 0
  exim_check_enable: 0
  kamailio_check_dialog_active_enable: 1
  kamailio_check_dialog_early_enable: 0
  kamailio_check_usrloc_regusers_enable: 1
  kamailio_check_usrloc_regdevices_enable: 0
  oss_check_provisioned_subscribers_enable: 1

  force: 0
  mysql_check_replication: 1
  kamailio_check_dialog_local_enable: 0
  kamailio_check_dialog_relay_enable: 0
  kamailio_check_dialog_incoming_enable: 0
  kamailio_check_dialog_outgoing_enable: 0


  collcheck:
    maxage: 600
    cpuidle: 0.1
    swapfree: 0.5
    dfused: 0.9
    memused: 0.7
    loadshort: 3
    loadmedium: 2
    loadlong: 2
    siptimeout: 15
    eximmaxqueue: 15

cdrexport:
  exportpath: '/home/jail/home/cdrexport'
  filepreffix: sipwise
  fileversion: 001
  monthly_folder: yes
  daily_folder: yes
cleanuptools:
  batch: 10000
  archive_targetdir: '/tmp'
  compress: gzip
  acc_days: 90
  trash_days: 30
  acc2_days: 180
general:
  companyname: sipwise
  lang: en
  adminmail: nomail@nodomain.org

# vim: ft=yaml
