#!/usr/bin/perl
# Purpose: report internal->fileformat setting of /etc/ngcp-config/config.yml
################################################################################

use strict;
use warnings;

use YAML::XS;

my $yaml = YAML::XS::LoadFile('/etc/ngcp-config/config.yml');
my $fileformat = $yaml->{internal}->{fileformat};

if (defined $fileformat) {
  print "$fileformat\n";
  exit 0;
} else {
  print "undefined\n";
  exit 1;
}

## END OF FILE #################################################################
