#!/usr/bin/perl -CSD
# Purpose: sort yaml configuration file
################################################################################

use strict;
use warnings;

use YAML::XS;

my $inputfile  = shift or die 'You did not specify an input file name';
my $outputfile = shift or die 'You did not specify an ouput file name';

my $yaml = YAML::XS::LoadFile($inputfile)
    or die "Could not read YAML to $inputfile";

YAML::XS::DumpFile($outputfile, $yaml)
    or die "Could not write YAML to $outputfile";

## END OF FILE #################################################################
