#!/bin/bash

NGCP_SOCKETFILE="${NGCP_SOCKETFILE:-/run/ngcpcfg.socket}"

if [ ! -e "$NGCP_SOCKETFILE" ] ; then
  echo "ERROR: Wrong ngcpcfg tt2-daemon socket file: $NGCP_SOCKETFILE" >&2
  exit 1
fi

echo "$@" | netcat -U "$NGCP_SOCKETFILE"

exit $?
