#!/usr/bin/perl -CSD
# Purpose: validate yml file format
################################################################################

use strict;
use warnings;

use YAML::XS;
use File::Temp qw/tempfile/;

my $inputfile  = shift or die 'You did not specify an input file name';
my $outputfile = new File::Temp( UNLINK => 1 );

my $yaml = YAML::XS::LoadFile($inputfile) or die "Could not read $inputfile\n".$yaml->errstr()."\n";
open my $fh, '>', $outputfile or die "Could not open $outputfile for writing";
print { $fh } YAML::XS::Dump($yaml) or die "Could not write YAML to $outputfile";

## END OF FILE #################################################################
