#!/usr/bin/perl -CSD
# Purpose: validate yml file format
################################################################################

use strict;
use warnings;

use YAML::XS;
use File::Temp qw/tempfile/;

my $inputfile  = shift or die 'You did not specify an input file name';
my $outputfile = new File::Temp( UNLINK => 1 );

my $yaml = YAML::XS::LoadFile($inputfile)
    or die "Could not read $inputfile\n";

YAML::XS::DumpFile($outputfile, $yaml)
    or die "Could not write YAML to $outputfile";

## END OF FILE #################################################################
