#!/bin/sh

set -eu

if ! ngcpcfg 2>&1 | grep -q 'Error: Configuration file' ; then
  echo "Assumed that /etc/ngcp-config/config.yml doesn't exist yet."
  exit 1
fi

cat > /etc/ngcp-config/config.yml <<EOF
---
test:
  - nothing
EOF

if ! ngcpcfg 2>&1 | grep -q 'Usage: ngcpcfg' ; then
  echo "ngcpcfg usage information not displayed."
  exit 1
fi
