#!/bin/bash
# Purpose: user interface for configuration management system
################################################################################

set -e
set -u

if [ "$UID" -ne 0 ] ; then
  printf "Error: ngcpcfg requires root permissions. Exiting.\n" >&2
  exit 1
fi

# support for testsuite
FUNCTIONS="${FUNCTIONS:-/usr/share/ngcp-ngcpcfg/functions/}"
SCRIPTS="${SCRIPTS:-/usr/share/ngcp-ngcpcfg/scripts/}"

if ! [ -r "${FUNCTIONS}/main" ] ; then
  printf "Error: ${FUNCTIONS}/main could not be read. Exiting.\n" >&2
  exit 1
fi

if [[ "${1:-}" == "decrypt" ]] ; then
  # do NOT source ${FUNCTIONS}/main but just provide
  # the part we need for executing ngcpcfg itself
  log_debug() {
    if [ -n "${DEBUG:-}" ] ; then
      logger -t ngcpcfg -- "Debug: $*"
      echo ; echo "DEBUG: $*" ; echo # newlines to avoid messup with cmdline output
    fi
  }
else
  . ${FUNCTIONS}/main
fi

# helper functions

action() {
  ACTION="$1"
  shift
  log_debug "${SCRIPTS}/${ACTION} $@"
  "${SCRIPTS}/${ACTION}" "$@"
}

usage() {
  # make sure to output errors on stderr
  [ "${1:-}" = "1" ] && exec >&2

  printf "%s - Configuration Management System\n\n" "$PN"
  printf "Usage:

  $PN build [opts]    - generate/update configuration files
  $PN commit [msg]    - commit and record changes (without pushing)
  $PN diff [opts]     - display pending configuration changes
  $PN help            - display this help screen and exit
  $PN version         - display program version and exit
  $PN initialise      - initialise setup (to be executed only once on setup)
  $PN check           - validate YAML configuration files
  $PN values          - print key value from YAML configuration files
  $PN log [opt]       - show log of config changes
  $PN show [id]       - show latest config change (if id is specified show specified id instead)
"

  # display only if ngcp-ngcpcfg-ha is available
  if [ -r /usr/share/ngcp-ngcpcfg/functions/ha_features ] ; then
    printf "  $PN push [opts]     - push modifications to other systems (shared storage setup only)\n"
    printf "  $PN pull            - retrieve modifications from shared storage (shared storage setup only)\n"
  fi

  # display only if ngcp-ngcpcfg-locker is available
  if [ -r /usr/share/ngcp-ngcpcfg/scripts/encrypt ] ; then
    printf "  $PN encrypt         - encrypt /etc/ngcp-config and all resulting configuration files\n"
    printf "  $PN decrypt         - decrypt /etc/ngcp-config-crypted.tgz.gpg and restore config files\n"
  fi

  # display only if ngcp-ngcpcfg-carrier is available
  if [ -r /usr/share/ngcp-ngcpcfg/scripts/init-mgmt ] ; then
    printf "  $PN init-mgmt <srv> - set up mgmgt server for carrier environment (to be executed only once)\n"
  fi

  printf "  $PN services [opts] - execute service handlers for modified configuration files
  $PN apply           - a short-cut for check-build-services-commit
  $PN status          - display status of configuration file\n\n"

  printf "For further usage information and options visit the ngcpcfg manpage.\n"
}

version() {
  versinfo=$(dpkg --list ngcp-ngcpcfg 2>/dev/null | awk '/^ii/ {print $3}')
  [ -n "${versinfo:-}" ] || versinfo='information not available'
  printf "ngcpcfg, version ${versinfo}\n"
}

case ${1:-} in
  apply|\
  build|\
  check|\
  commit|\
  decrypt|\
  diff|\
  encrypt|\
  init-mgmt|\
  initialise|\
  log|\
  pull|\
  push|\
  services|\
  show|\
  status|\
  values)
    action "$@" ;;
  --debug)         export DEBUG=1 ;      shift ; $0 $* ;;
  --no-db-sync)    export NO_DB_SYNC=1 ; shift ; $0 $* ;;
  --no-validate)   export NO_VALIDATE=1; shift ; $0 $* ;;
  --no-action-failure) export NO_ACTION_FAILURE=1; shift ; $0 $* ;;
  -h|--help|help)       usage   ; exit 0;;
  -v|--version|version) version ; exit 0;;
  *)          usage 1; exit 1;;
esac

## END OF FILE #################################################################
