#!/bin/bash
# Purpose: decrypt ngcp configuration archive
################################################################################

set -e
set -u
set -o pipefail

# support for testsuite, assume defaults if unset
FUNCTIONS="${FUNCTIONS:-/usr/share/ngcp-ngcpcfg/functions/}"
HELPER="${HELPER:-/usr/share/ngcp-ngcpcfg/helper/}"

if ! [ -r "${FUNCTIONS}"/logs ] ; then
  printf "Error: %s/logs could not be read. Exiting.\n" "${FUNCTIONS}">&2
  exit 1
fi

# We cannot source ${FUNCTIONS}/main as we are missing a bunch of
# configuration files that are supposed to be available, therefore we
# source the ${FUNCTIONS}/logs file instead.

timestamp_replacementchars='' # unset by default
# shellcheck disable=SC1090
. "${FUNCTIONS}"/logs

setup_shared_config() {
  if ! [ -d /mnt/glusterfs/mgmt-share ] ; then
    log_warn "Looks like glusterfs is not running, can not install it automatically.

Please execute the following command on one node
as soon as glusterfs share is mounted again:

  git clone --bare /etc/ngcp-config /mnt/glusterfs/ngcpcfg-share
  ${HELPER}/restore-permissions /mnt/glusterfs/ngcpcfg-share

"
    return 0
  fi

  if [ -d /mnt/glusterfs/ngcpcfg-share ] ; then
    log_info "Shared storage exists already, ignoring request to (re)install it."
  else
    log_info "Copying git repository to shared storage."
    git clone --bare /etc/ngcp-config /mnt/glusterfs/ngcpcfg-share | sed "s/^/${timestamp_replacementchars}/"
    "${HELPER}"/restore-permissions /mnt/glusterfs/ngcpcfg-share
  fi
}

# main script
if ! type -p gpg &>/dev/null ; then
  log_error "gpg binary not found, exiting."
  exit 1
fi

RC=0
TARGZ=/etc/ngcp-config-crypted.tgz

# ensure created files can be read by root only
umask 066

if ! gpg -d "${TARGZ}".gpg > "${TARGZ}" ; then
  log_error "Error while decrypting ${TARGZ}.gpg"
  RC=1
else
  # For backwards compatibility we switch to the root directory, for old
  # encrypted tarballs that stripped the leading /.
  cd /
  if tar zxPf "${TARGZ}" ; then
    log_info "Successfully restored configuration archive ${TARGZ}.gpg"
    log_info "Now you should be able to run 'ngcpcfg apply' again."
  else
    log_error "Error while restoring ${TARGZ}.gpg"
    RC=1
  fi
fi

# only for PRO/CARRIER
if [ -r "${FUNCTIONS}"/ha_features ] ; then
  setup_shared_config
else
  log_info "Ignoring shared configuration (PRO/CARRIER only)."
fi

# don't leave the unencrypted archive behind
rm -f "${TARGZ}"

exit "${RC}"

## END OF FILE #################################################################
