#!/bin/bash
# Purpose: show ngcpcfg log (git log) in human readable format
################################################################################

set -e
set -u

# support testsuite
FUNCTIONS="${FUNCTIONS:-/usr/share/ngcp-ngcpcfg/functions/}"
HELPER="${HELPER:-/usr/share/ngcp-ngcpcfg/helper/}"

if ! [ -r "${FUNCTIONS}"/main ] ; then
  printf "Error: %s/main could not be read. Exiting.\n" "${FUNCTIONS}" >&2
  exit 1
fi

. "${FUNCTIONS}"/main

host="${1:-localhost}"
log_cmd="git log --oneline --date-order --graph "

cd "$NGCPCTL_MAIN"

if [ "${host}" = "localhost" ] ; then
  $log_cmd
else
  ssh "${host}" "cd $NGCPCTL_MAIN ; ${log_cmd}"
fi

exit 0

## END OF FILE #################################################################
