#!/bin/bash
# Purpose: set config value
################################################################################

set -e
set -u

# support testsuite
FUNCTIONS="${FUNCTIONS:-/usr/share/ngcp-ngcpcfg/functions/}"
HELPER="${HELPER:-/usr/share/ngcp-ngcpcfg/helper/}"
SCRIPTS="${SCRIPTS:-/usr/share/ngcp-ngcpcfg/scripts/}"

if ! [ -r "${FUNCTIONS}"/main ] ; then
  printf "Error: %s/main could not be read. Exiting.\n" "${FUNCTIONS}">&2
  exit 1
fi

# shellcheck disable=SC1090
. "${FUNCTIONS}"/main

## functions {{{
help() {
  echo "Usage: ngcpcfg set [<options>] <file> <key>"
  echo "Example: ngcpcfg set /etc/ngcp-config/config.yml general.maintenance=yes"
  echo "Options:"
  echo "  --diff: show difference(s) for the applied changes"
}

## }}}

RC=0
b_show_diff=false

while [ -n "${1:-}" ]; do
  case "$1" in
    --diff)
      b_show_diff=true
      shift
      ;;
    --*)
      log_error "unsupported option '$1'. Exiting."
      help >&2
      exit 1
      ;;
    *)
      break
      ;;
  esac
done

if [ "${#:-}" != "2" ]; then
  help >&2
  exit 1
fi

file="$1"
data="$2"

[ -f "${file}" ] || (log_error "missing ${file}. Exiting." ; exit 1)
[ -z "${data}" ] && (log_error "missing data to set. Exiting." ; exit 1)

# Check whether we should use different permissions when creating the file.
CREATEFILE=no
if [ ! -f "${file}" ]; then
  CREATEFILE=yes
  if [ "${file}" = "${NETWORK_CONFIG:-}" ]; then
    MODE="${NETWORK_CONFIG_CHMOD}"
    USER="${NETWORK_CONFIG_USER}"
    GROUP="${NETWORK_CONFIG_GROUP}"
  else
    MODE="${CONFIG_CHMOD}"
    USER="${CONFIG_USER}"
    GROUP="${CONFIG_GROUP}"
  fi
fi

log_debug "Received data: ${data}"
option="${data%%=*}"
value="${data#*=}"
log_debug "Parsed option: ${option}"
log_debug "Parsed value: ${value}"

[ -z "${option}" ] && ( log_error "missing option to set. Exiting." ; exit 1)
[ -z "${value}" ] && ( log_error "missing value to set. Exiting." ; exit 1)
log_debug "Saving option '${option}' value '${value}' into '${file}'"

log_debug "${HELPER}/set-value '${file}' '${option}' '${value}' || RC=\$?"
"${HELPER}/set-value" "${file}" "${option}" "${value}" || RC=$?

if [ "${CREATEFILE}" = "yes" ]; then
  chmod "${MODE}" "${file}"
  chown "${USER}" "${file}"
  chgrp "${GROUP}" "${file}"
fi

if [ "${RC}" = "0" ] && "${b_show_diff:-false}"; then
  log_debug "${SCRIPTS}/diff || true"
  "${SCRIPTS}"/diff || true
fi

exit ${RC}

## END OF FILE #################################################################
