#!/bin/bash
# Purpose: get a value based on ngcpcfg's config
################################################################################

set -e
set -u

# support testsuite
FUNCTIONS="${FUNCTIONS:-/usr/share/ngcp-ngcpcfg/functions/}"
HELPER="${HELPER:-/usr/share/ngcp-ngcpcfg/helper/}"

if ! [ -r ${FUNCTIONS}/main ] ; then
  printf "Error: ${FUNCTIONS}/main could not be read. Exiting.\n" >&2
  exit 1
fi

. ${FUNCTIONS}/main

# Kill all previous started tt2-daemon Perl processes if they were not stopped properly
killall tt2-daemon 2>/dev/null || true
rm -f /var/run/ngcpcfg.port

# Start new tt2-daemon Perl process
${HELPER}/tt2-daemon

# Load all the configs in proper order and check their avialability and valid YAML syntax
for f in ${NGCPCTL_CONFIG:-} ${HOST_CONFIG:-} ${LOCAL_CONFIG:-} ${NETWORK_CONFIG:-} ${EXTRA_CONFIG_FILES:-} ${CONSTANTS_CONFIG:-} ; do
  if [ -r "$f" ] ; then
    if ! "${HELPER}/tt2-wrapper" "/dev/null" "${f}" ; then
      log_error "tt2-daemon cannot load ${f}:"
      "${HELPER}/tt2-wrapper" "/dev/null" "${f}"
      exit 1
    fi
  fi
done

# main script
RC=0

# assume safe defaults
umask 0077

input_file="$(mktemp)"
echo "[% ${key} %]" > input_file
output_file="$(mktemp)"

TT_WRAPPER="${HELPER}/tt2-wrapper"

if "$TT_WRAPPER" "${input_file}" > "${output_file}" 2>/dev/null ; then
  cat "${output_file}"
else
  RC=1
fi

rm -f "${input_file}" "${output_file}"

# Kill all previous started tt2-daemon Perl processes
killall tt2-daemon 2>/dev/null || true
rm -f /var/run/ngcpcfg.port

exit "$RC"

## END OF FILE #################################################################
